CONTRIBUTING.md
NOTICE.md
README.md
mix-manifest.json
package-lock.json
package.json
webpack.mix.js

Change-Id: I9baff15444bca4484fd7ec612029d097d020d9e6

Add contributing.md

---

CONTRIBUTING.md
NOTICE.md
README.md
package-lock.json
package.json
webpack.mix.js

Change-Id: I0588d4caf70437f912e73c064d7923773844e2bc

Add Cookie Consent

---

docs/index.html
js/solstice.googletagmanager.js
js/solstice.wiki.js
less/_components/classes-grid.less
less/_components/main-menu.less
less/quicksilver/forums.less
less/quicksilver/mediawiki/print.less
less/quicksilver/mediawiki/styles.less
less/quicksilver/mediawiki/template.less
webpack.mix.js

Change-Id: I2bef8140926c33c87365698a64c174707e00f390

Add mediawiki and forums to quicksilver

---

package-lock.json
package.json

Change-Id: I444c795e62d5b039558bc658d9b1c80961b51c8f

prepare for 0.0.27

---

js/eclipsefdn.videos.js

Change-Id: I5890c722a687cb7618715228c34679ff89d2e43c

convert video only if user allows cookies

---

less/_components/drupal/user-profile.less
less/quicksilver/_variables.less

Change-Id: I96413b0aa4c0db0ca97b4c8ee089feafc536e75e

Update styles for list links and title of user profile

---

less/_components/classes.less
less/_components/eclipsefdn-video.less
less/quicksilver/styles.less
less/solstice/styles.less

Change-Id: I009c42af13c721d00620d09d010e8ffdb45ee5c1

Bug 535290 - Create separate file for eclipsefdn videos

---

less/_components/bootstrap/drupal.less
less/_components/bootstrap/tabs.less
less/_components/drupal/call-for-action.less
less/_components/drupal/news-events.less
less/drupal.less
less/quicksilver/_variables.less
less/quicksilver/drupal.less
less/quicksilver/template.less

Change-Id: I562c030bf4ba80bb45d44f7e1319ae8f459d31e5

Improvements for blogs.eclipse.org

---

js/solstice.js

Change-Id: I3e369b6a388d77068ed91822fdbf0a6307e70203

Add Show/hide more items functionality

---

less/_components/bootstrap/buttons.less

Change-Id: Ifeabd0c2bf3d9a851ea0cbea50b1f7798fd6eb67

Apply text color white on button when focus

---

less/quicksilver/_variables.less

Change-Id: I5f9ac18ee0d8bbc3142e51c923118b4295f52639

Bug 536190 - Update styles for eclipse.org home page jumbotron

---

js/solstice.cookieconsent.js
js/solstice.js
less/_components/user-toolbar.less
less/quicksilver/_variables.less
less/quicksilver/template.less

Change-Id: I4c27acc79212b1229f44bd5b63bb91ad6ffa55dd

Bug 534685 - Update styles for the toolbar in Quicksilver

---

js/solstice.js
less/quicksilver/template.less

Change-Id: I38e8abffa11d7a4c472c9b0a21b55e6c5db78979

Bug 534685 - Update classes for toolbar dropdown

---

js/solstice.js

Change-Id: Icac9c3642a055b1e2eb4d2d629160f6c63fe0391

Infra 2791 - Send events to google analyics

---

js/solstice.cookieconsent.js
webpack.mix.js

Fix missing cookie banner

---

js/solstice.js

Change-Id: If77d9cfc12304e13fa7a7a167efbeab5de70440d

Fix issue with link click for GA events

---

js/solstice.js

Fix event tracker

---

less/_components/quicksilver/featured-stats.less
less/quicksilver/drupal.less
less/quicksilver/styles.less

Bug 2899 - Add key metrics summary to eclipse.org

---

less/_components/drupal/listing.less
less/_components/drupal/menu-item-list.less
less/quicksilver/marketplace/_variables.less
less/quicksilver/marketplace/drupal.less
less/quicksilver/marketplace/template.less

Change-Id: Ic4647dd8ba8f84fee1f47cf99017c4f8eda5f236

Migrate marketplace styles to quicksilver

---

less/_components/quicksilver/featured-centered-item.less

Change-Id: I438fd05e517108de818d1eae29a4163ec39b8477

Bug 538653 - Update styles for front page of newsletter

---

stylesheets/eclipsecon/_core/components/schedule.less

Change-Id: If405d453f5b21a31cd889bdba7575086c10ca70e

Infra 2966 - Update icon track colors

---

package.json

Change-Id: I04c78a807c0f11eecf630c623309064a851df659

Use laravel mix v2.1.11

---

less/_components/quicksilver/featured-centered-item.less
less/quicksilver/openpass/_variables.less
less/quicksilver/projects/_variables.less
less/quicksilver/projects/drupal.less
less/quicksilver/projects/pmi.less
less/quicksilver/template.less

Change-Id: I592dfd24feb09b8d0df5c9117d6b5d46db339135

Migrate projects styles to Quicksilver

---

less/quicksilver/projects/drupal.less

Change-Id: Ib955f340355612157bd091d18af91bcaf943e7b5

Fix panels text for projects website

---

less/_components/drupal/blocks.less
less/_components/drupal/members.less
less/_components/drupal/news-events.less
less/_variables.less
less/quicksilver/_variables.less
less/quicksilver/locationtech/_variables.less
less/quicksilver/locationtech/drupal.less
less/quicksilver/locationtech/template.less
less/quicksilver/openpass/_variables.less
less/quicksilver/projects/_variables.less
less/quicksilver/template.less

Change-Id: Iab98149f51409b02180ca7f924c9a61a76d169ed

Migrate locationtech styles to Quicksilver

---

less/_components/bootstrap/buttons.less
less/_components/quicksilver/featured-stats.less

Change-Id: I06ad0578646ca16b45990c82f5cc2f7651cdf0bc

Infra 3039 - Add/Update styles for EclipseIDE page

---

less/_components/quicksilver/featured-centered-item.less

Change-Id: I4c8dde1983d50c3dd17909acb6b2ea3f912f3886

Fix newsletter page styles

---

less/quicksilver/template.less

Change-Id: Ia5941c9bcfb68cbb8b121426b7fdd8892f74aa0b

Bug 541853 - Fix spacing for dropdown menu items

---

less/_components/eclipse_org/newsletter-page.less

Change-Id: Ief1ad31add778af9222142969365a31da56efd50

Remove nowrap for newsletter subtitle

---

less/quicksilver/jakarta/template.less

Change-Id: I2dd5b50abd79436382c870fc1fb85fd7a2fac1e8

Update Jakarta EE styles

---

package-lock.json
package.json

Update bootstrap and webpack

---

less/_components/drupal/blocks.less

solstice block margin updated to 20px

---

js/solstice.js

Change-Id: Id8c09dfab89e76cb320f00f428282772e0874b53

Add default classes for matchHeight

---

less/_components/bootstrap/buttons.less
less/_components/classes-colors.less

Change-Id: I7743a823c332c108daf5c1a1e7a3b812b9cac232

Create grey button class

---

less/_components/quicksilver/featured-jumbotron.less
less/_components/quicksilver/featured-story.less
less/quicksilver/_variables.less

Change-Id: I1574484ddc1183e3b32cd139bb5fd2f62eefc128

Standardize the featured story section

---

stylesheets/eclipsecon/_core/components/session.less

Change-Id: Id83e7ca065b0ff55949da7e876eee17fefe46653

Update margin for Session fields

---

js/solstice.js
less/_components/quicksilver/block-list.less
less/_components/quicksilver/news-list.less
less/_variables.less
less/quicksilver/_variables.less
less/quicksilver/jakarta/_variables.less
less/quicksilver/projects/_variables.less
less/quicksilver/styles.less

Change-Id: I56a742e80d854ebd01abd8d6b2f84b361c23a807

Create styles for block list

---

less/_components/quicksilver/block-list.less
less/_components/quicksilver/featured-footer.less
less/_components/quicksilver/featured-jumbotron.less
less/_components/quicksilver/featured-story.less
less/_components/quicksilver/news-list.less
less/_variables.less
less/quicksilver/_variables.less
less/quicksilver/jakarta/_variables.less
less/quicksilver/projects/_variables.less

Change-Id: Icf1d63803f84c27c2f7e245d7c49891150a0e541

Remove shapes from quicksilver layout

---

js/solstice.js

Change-Id: Idc7405d9cd40a22cfbe44f5c24d66d5716a3cc1a

Use proper selector for block-summary items

---

less/_components/bootstrap/badges.less
less/drupal.less
less/quicksilver/styles.less
less/solstice/forums.less
less/styles.less

Change-Id: Icfd9467325478457e1f3c26197a66331c873d975

Override Bootstrap badges and create new ones

---

.travis.yml
package-lock.json
package.json

Remove cache to detect problems early.

update cookieconsent and yamm

---

.travis.yml

update travis build script

---

less/drupal.less
less/quicksilver/_barebone/core.less
less/quicksilver/styles.less
less/solstice/_barebone/core.less
less/styles.less
package-lock.json
package.json

fix dependencies

---

less/_components/classes-grid.less

Updated grid classes to have some minor flex functionality.
Change-Id: If7966f994357cde122d5f403aaab78904aebbfb0

Infra 3246 - Add Individual WGPA on explore page

---

less/_components/drupal/site-login-user-menu.less

Change-Id: I2f534b56369c4ac851c21f883861cb6d644a1ac6

Update styles for user account sub menu

---

less/quicksilver/_variables.less

Change-Id: I2b378cd876a639b38fdb63c44a2dbb4c8b689a25

Content background is same color as striped table accent #83

---

less/_components/quicksilver/featured-jumbotron.less
less/_variables.less

Change-Id: I810ffa2a0574285fa637e70aae0799a4f8c37228

Create jumbotron alternate styles

---

less/_components/quicksilver/project-list.less
less/quicksilver/styles.less

Change-Id: Ib0233b8ccbacbb18f0a317d2ca5809141259fed8

Added project-list styling

---

less/_components/conference/news-events.less
less/_components/conference/schedule.less
less/_components/drupal/user-profile.less
less/_variables.less
less/quicksilver/conference/_variables.less
less/quicksilver/conference/drupal.less
less/quicksilver/conference/template.less

Change-Id: I87999ee1f8b0e2e5cc84b1f5d8e5d31c58576bbb

Infra 3043 - Migrate Eclipsecon Theme to Quicksilver

---

less/_components/quicksilver/featured-story.less

Change-Id: Ia15e067aab09d4be6f230981d636fafc9689940b

Fix featured story background image

---

less/_components/quicksilver/featured-story.less

Change-Id: I2ec3b4ca94f08437349381935c3166e97eefc545

Update styles for featured story and featured ad

---

less/_components/classes-typography.less
less/_variables.less
less/quicksilver/jakarta/_variables.less

Added header highlight class, along with 2 customization variables.
Change-Id: Ia6fff2402c3fbc8e0ccede3a7387b187ca0bc5fd

Added highlight class to quicksilver

---

js/solstice.tables.js

Added JS to inject table classes in main section of the page. Variable
used to set table classes is `tableClasses`.
Change-Id: I97e76ced51c25642e0fe89ba19cadf8b34f04039

Added JS to inject table classes

---

less/quicksilver/jakarta/_variables.less

Change-Id: I6e3ab33d23278ae70f90abac7dd4617f1d30fa3a

Fix for default btn font weight in Jakarta

---

less/quicksilver/jakarta/_variables.less

Change-Id: Ic3ce0a04f8fb90f18061644ebf7c22deb53025d6

Fix featured story

---

less/_components/quicksilver/featured-stats.less
less/quicksilver/jakarta/_variables.less
less/quicksilver/jakarta/template.less

Change-Id: Id7c0cc8897ec5df947807242d29be67a490b79d1

Update for Jakarta EE Pillars page

---

less/_components/quicksilver/featured-story.less

fix featured story padding

---

.travis.yml
package-lock.json
package.json

fix build issue with less

---

less/_components/quicksilver/featured-footer.less
less/_variables.less
less/quicksilver/jakarta/_variables.less

Jakarta.ee#404 Updates to enable featured footer

---

less/quicksilver/jakarta/template.less

clean up jakarta.ee

---

less/quicksilver/jakarta/_variables.less
less/quicksilver/jakarta/template.less

Change-Id: Ia360ead293189a19cf654a8ee782ed93504f30cb

Updated footer colours to be gray while maintaining icons

---

less/quicksilver/openpass/styles.less
less/quicksilver/science/styles.less

add science + openpas style

---

less/_components/footer.less

Change-Id: Ie0f8f5c5efb969d848e8c3815985b9146a44c59f

Bug 548884 - Apply position absolute to footer-min for big screens only

---

webpack.mix.js

test with papyrus_ic/drupal.less

---

less/_components/footer.less

Change-Id: Ib982ef5680ef6b5cbf110bd2d7d7db5bce08d1c0

Bug 550976 - Remove margin bottom for footer-min

---

less/quicksilver/packages/components/downloads.less
less/quicksilver/packages/components/thankyou.less

Change-Id: Ibd5eb6304b8792e15ece136fd05bb57b506192e9

Bug 551312 - Update newsletter class for adblocker

---

js/eclipsefdn.adopters.js

Change-Id: I042f7516293f6a685b71f7fbf0a19d32403abbc3

Add adopters plugin

---

js/eclipsefdn.formabandonment.js

Change-Id: I2e8e8a255830f2167cecfe14a408bb247399824b

Infra 3361 - Add Form Abandonment JS file

---

less/_components/conference/sponsors.less

Change-Id: Ie0ec5e8ca96f0251e2531fb6f5912755056ffe1f

Infra 3428 - Add styles for 3 sponsors block for ECE

---

js/eclipsefdn.videos.js

Change-Id: I128c36c4ebbb0454a3252a5b5df5f9ebac771475

Fix youtube videos

---

js/solstice.js

Change-Id: I2a086e5ee72586da4d00e20963ee9cfc3244ed21

Bug 551848 - Fix clickable block-summary-item elements

---

less/_components/bootstrap/buttons.less
less/_components/classes-typography.less

Added CSS needed for agenda component

---

less/_components/quicksilver/featured-testimonials.less
less/_variables.less
less/quicksilver/styles.less

Change-Id: I949c1f059367b56263d5adb512f7c48789898d07

Add testimonials components

---

less/_components/quicksilver/event-timeline.less
less/quicksilver/_variables.less
less/quicksilver/styles.less

Change-Id: If3befd3415e99ae20f198b91d8d75ffca10f2523

Add timeline component

---

js/solstice.js
less/_components/classes.less
less/_variables.less

Added RSS feed JS + styled loading container

---

less/quicksilver/europe2020/_components/slideshow.less

Change-Id: I983e17b2e9aa2c9a5e362ddabaa782daf7050c36

Infra 3637 - Update styles for ECE2020 jumbotron

---

less/quicksilver/europe2020/drupal.less
package.json

Change-Id: Ifaaed101d90b1f6540526b7c437722ada80c2d88

Infra 3637 - Add Owl and Lightbox2

---

less/quicksilver/europe2020/_components/slideshow.less
less/quicksilver/europe2020/_variables.less
less/quicksilver/europe2020/drupal.less

Change-Id: I7c880cff87e2651203971996867d836d8e6979d1

Infra 3656 - Update styles for Eclipsecon europe 2020

---

less/drupal.less
less/quicksilver/europe2020/drupal.less

Change-Id: I12013403be92843a5a6b9e6a117a73fd32a0d8d0

Move owl and lightbox to drupal core theme

---

less/_components/conference/schedule.less

Change-Id: I706d95d0c869e0abe2bddbcf853bdfbc613583a5

Infra 3696 - Apply pointer cursor only for eclipscon schedule

---

less/_components/conference/speakers.less
less/quicksilver/europe2020/drupal.less

Change-Id: I18a3dc9f534437dfe3f737f6c0b7b46e1a5061b5

Add styles for Speakers in EclipseCon 2020

---

less/quicksilver/styles.less

Change-Id: I33c195ae9f9da1e154f89ce2a9c2a5eb4be6c6f1

Infra 3699 - Add Owl for eclipse.org

---

less/_components/quicksilver/featured-story.less

Added alternate class for ad/side content to bypass ad blocker

---

js/solstice.js
webpack.mix.js

Change-Id: I9aea28a1fec7c2c5bb4379cf8895ccc64fa80375

Infra 3699 - Add missing Owl JS library

---

package.json

Change-Id: I9fd3f282032a7cb8098a575d56f6862f7b8d1d26

Making sure we are using jquery 3.3.1

---

js/solstice.js

Change-Id: I0407988f4fbc0f9ff4fcab6b2fd907281bae0aef

news block should be clickable anywhere

---

js/solstice.eventsmodal.js
webpack.mix.js

Added modal JS to webpack code

---

js/solstice.js
less/_components/classes-grid.less
less/_components/classes-typography.less

Added icon backdrop class, which gives a block element with an icon that
grows and shrinks based on viewport (ported from IoT). Added new layout
class of centered container which vertically aligns without flex for
containers that aren't easily shifted by vertical-align rule. Updated
solstice slider to have 4 images at max breakpoint.

Tweaks to classes for events base implementation

---

less/_components/quicksilver/featured-section.less
less/quicksilver/_variables.less
less/quicksilver/styles.less

Change-Id: I7298c37ed141fd18b14ebb0c2e98c8f725374015

Add featured section classes

---

js/solstice.eventsmodal.js
less/_components/classes-typography.less
less/_components/events/eclipsefdn-agenda.less
less/_components/events/eclipsefdn-registration.less
less/_components/events/eclipsefdn-user-display.less
less/_components/quicksilver/featured-section.less
less/quicksilver/_variables.less
less/quicksilver/styles.less

Change-Id: Iee813876057b3ef238f8d012f07fc06b55b8415c

Initial commit of default event template css

---

less/_components/events/eclipsefdn-sponsors.less
less/quicksilver/_variables.less
less/quicksilver/styles.less

Added sponsor CSS for list display with optional width max class

---

less/_components/quicksilver/featured-section.less
less/quicksilver/_variables.less

Change-Id: I43f61badf2aa1d2e21e2482653c00189d2a44bff

Fix links in dark featured sections

---

less/quicksilver/marketplace/template.less

Change-Id: Ic09ed4be71c1487ea8cd5402c9d32404ecc438d1

Add styles for resource listing release field on marketplace

---

less/_components/quicksilver/featured-section.less

Fix for featured section button text being off coloured

---

less/_components/conference/speakers.less
less/_components/conference/sponsors.less
less/quicksilver/conference/_variables.less
less/quicksilver/europe2020/_variables.less
less/quicksilver/europe2020/template.less

Change-Id: I98c3032d2c624e6b7a8f2efad151776bf841408f

Infra 3774 - Add styles for conference sponsors

---

docs/index.html
js/solstice.js
less/_components/bootstrap/buttons.less
less/_components/classes-blocks.less
less/_components/classes-colors.less
less/_components/classes-grid.less
less/_components/quicksilver/content-nav-tab.less
less/_components/quicksilver/section-highlights.less
less/_variables.less
less/quicksilver/_variables.less
less/quicksilver/styles.less

Added content-nav-tab component, updated section highlights, and colors

---

less/quicksilver/_variables.less

Change-Id: Ie77f5a9c572bdf6408f98761b7fc5154feac739d

Use Roboto as base-font

---

less/quicksilver/conference/_variables.less

Fix #151
Change-Id: Id6694ff462287e72cfeaf0702945a2c3f1d48547

Link color updates - Eclipsecon.org #151

---

docs/index.html
less/quicksilver/jakarta/_variables.less
less/quicksilver/projects/_variables.less

completely remove Libre Franklin

---

less/quicksilver/europe2020/_variables.less

Update color on EclipseCon 2020 schedule #158

---

less/_components/conference/sponsors.less

Change-Id: Id3a968d9061caed6874e1639cf3b2ed5f78fac1b

Infra 3774 - Fix padding for sponsors logos on mobile

---

less/quicksilver/mediawiki/template.less

Change-Id: I4862e296681c43bd8ade454eebd19d948af01dae

Bug 565171 - Wiki page authors red on grey is unreadable

---

less/_components/eclipse-installer.less
less/quicksilver/packages/components/downloads.less

Change-Id: I95886f4b89f88fcf234b1cf32f60ea993ed22d09

Bug 566450 - Create styles for Installer alert boxes

---

less/_components/eclipse-installer.less
less/quicksilver/packages/components/downloads.less

Change-Id: I5e95c1c7f8b334a9cdfd541c5042a1bd293799b8

Update location of eclipse installer alert class

---

less/quicksilver/europe2020/drupal.less

Change-Id: Id9127d77a051bf410c4fdc3c4dd1520aee53be08

Add eclipsefdn videos to EclipseCon 2020

---

less/_components/footer.less
less/quicksilver/template.less

Change-Id: I6f7247d7475fda8fe59977e68849cc6f35245f5f

Fix mobile footer alignement

---

js/eclipsefdn.render-rss-feeds.js
js/solstice.js

hot fix for previous renderRSSFeeds() patch

---

js/solstice.js

to Fix https://github.com/EclipseFdn/hugo-solstice-theme/issues/175
and it's a combination with https://github.com/EclipseFdn/jquery-eclipsefdn-api/pull/30 and https://github.com/jakartaee/jakarta.ee/pull/922

Fix news mh-group not working

---

js/solstice.js

To Fix https://github.com/jakartaee/jakarta.ee/issues/749

move func match-height in windows onload

---

docs/index.html

Add dropdowns in toolbar for testing

---

less/_components/classes-flex.less
less/_components/classes-grid.less
less/_components/classes.less

Add classes and create flex file

---

less/_components/quicksilver/resources-group.less
less/quicksilver/styles.less

Change-Id: I3e3c9153569aaf32b1f2f534bff2656657528d54

Add resources styles

---

less/_components/quicksilver/eclipsefdn-adopters.less
less/quicksilver/styles.less

add eclipsefdn-adopters styles

---

js/eclipsefdn.adopters.js
webpack.mix.js

to support https://github.com/EclipseFdn/hugo-solstice-theme/pull/190
I replace the original `eclipsefdn.adopters.js` with https://github.com/EclipseFdn/eclipsefdn-project-adopters/blob/master/js/eclipsefdn.adopters.js

add adopters js

---

less/_components/buttons.less
less/_components/classes-padding-margin.less

add spacing to buttons using list-inline on mobile view

---

js/eclipsefdn.adopters.js

add missing / for project url

---

less/_components/quicksilver/eclipsefdn-adopters.less
less/_variables.less

add variables to custom adopters

---

js/eclipsefdn.adopters.js

Fix https://github.com/EclipseFdn/hugo-solstice-theme/issues/191

add id to project header

---

js/eclipsefdn.ads.js
webpack.mix.js

Change-Id: Ic7b81de07c1d142a5625edb153b567eb6df0c441

Initialize Ads plugin

---

.gitignore
docs/iot-adopters.html
js/eclipsefdn.adopters.js

Fix https://github.com/EclipseFdn/eclipsefdn-project-adopters/issues/39
Some test links:
https://deploy-preview-207--eclipsefdn-solstice-assets.netlify.app/iot-adopters.html#iot.leshan
https://deploy-preview-207--eclipsefdn-solstice-assets.netlify.app/iot-adopters.html#iot.paho

fix anchor and move scroll function in adopters js

---

js/eclipsefdn.adopters.js

remove console log

---

less/_components/bootstrap/badges.less

Change-Id: Ifb5c2f536bcf933a256e4a42cd9071d233cece67

Add badge notifications

---

less/_components/bootstrap/badges.less
less/_variables.less

Change-Id: Ia16268a0dc0c3a0d0f16d97ca74f47e72eb58ef5

Add variables to badge classes

---

.travis.yml
babel.config.json
js/eclipsefdn.adopters.js
package-lock.json
package.json
webpack.mix.js

fix for compile and use appendChild for IE comp

---

README.md
package-lock.json
package.json

Current list covers ~93% of global market and can still likely be
trimmed down based on actual usage stats from Google Analytics.

Add list of proposed supported browsers along with a query for builds

---

js/eclipsefdn.adopters.js

fix project adopters

---

less/_components/drupal/blocks.less
less/_components/quicksilver/block-list.less

Change-Id: I43f44b97daa21aeda15d2e6aaab37d92cace4013

Make .solstice-block-white-bg accessible for eclipse.org

---

less/_components/bootstrap/alerts.less
less/drupal.less
less/quicksilver/styles.less
less/styles.less

Change-Id: I0a1799000393dc9d31dd394c0f88adad0b95f89d

Infra 4010 - Update styles for buttons in alert boxes

---

less/drupal.less

Change-Id: Ia464e09a4658b384ae56b47561e4215128ce477d

Add block list to drupal sites

---

less/_components/quicksilver/sidebar-block.less

Change-Id: I286719e4c63868ffded2c1c934fef7eec3407053

Update padding for sidebar block

---

less/_variables.less
less/quicksilver/_variables.less

Change-Id: Ia1e0dabb275fe538cd677ba2adf1554a115bb315

Fix spacing for the Featured Footer

---

less/_components/quicksilver/sidebar-block.less

Should be sidebar-block-text instead of sidebar-text

---

less/quicksilver/template.less

Change-Id: I3aca5a4dab581719a701000fa4917e67f6e7008b

Bug 571136 - Create class for sidebar children

---

less/_components/drupal/solstice-form-box-wrapper.less

Change-Id: I700151212bff424be0de6132db78ffe1e85f091e

Bug 4147 - Update styles for Organization field in registration page

---

less/_components/conference/sponsors.less
less/quicksilver/conference/_variables.less
less/quicksilver/eclipsecon/_variables.less
less/quicksilver/eclipsecon2021/_variables.less

Change-Id: I297f646420686ea67190567aea1ad9678612c0b8

Infra 4133 - Update styles for Sponsors in sidebar

---

less/_components/bootstrap/panels.less
less/quicksilver/styles.less

Change-Id: I5662ff854a4bed4df2730f3fb6eb9de623fe4281

Infra 4168 - Add styles for panels

---

less/_components/quicksilver/newsletter.less
less/quicksilver/_variables.less
less/quicksilver/newsletter/_variables.less

Change-Id: I3c6cf478d812c3308ebcded206cd13f4d6e9283b

Bug 570555 - Update newsletter styles for HTML page

---

package-lock.json
package.json

security fixes +  remove jquery-api

---

js/privacy/eclipsefdn.cookie-consent.js

fix cc for ie11

---

js/api/eclipsefdn.adopters.js
js/privacy/eclipsefdn.videos.js

update to better support drupal

---

less/_components/coming-soon.less
less/_components/footer.less
less/_variables.less
less/drupal.less
less/styles.less

add coming-soon styles

---

less/quicksilver/eclipsecon2021/_variables.less

Change-Id: I65414a12c849773c2a710f70de1e13f09a3840e1

Infra 4281 - Update CTA button styles for Econ 2021

---

docs/members.html
js/solstice/eclipsefdn.members-list.js

allow array of pl

---

js/solstice/eclipsefdn.scrollup.js
less/_components/back-to-top.less

Fixed the scroll up icon is hidden by Chat Bot icon issue.
With this patch, it would look like this:
Preveiw here: 
https://deploy-preview-312--eclipsefdn-react-members.netlify.app/

Fixed scroll up icon issue
